version: '3.8'

services:
  back:
    build:
      context: ./back
    ports:
      - "5000:5000"
  db:
    build: 
      context: ./database
    ports:
      - "5432:5432"
  front:
    build:
      context: ./front
    ports:
      - "3000:3000"
    depends_on:
      - back